version: "2.4"

services:
  redmine-x:
    image: registry.berlinonline.net/redmine_x/dockerimage:latest
    depends_on:
      database-setup:
        condition: service_completed_successfully
    environment:
      MYSQL_USER: &MYSQL_USER projectino
      MYSQL_HOST: &MYSQL_HOST percona
      MYSQL_PASSWORD: &MYSQL_PASSWORD 'something else'
      MYSQL_DATABASE: &MYSQL_DATABASE projectino
    ports:
      - "8080:9000"

  database-setup:
    pull_policy: build
    build: database-setup
    environment:
      MYSQL_USER: *MYSQL_USER
      MYSQL_HOST: *MYSQL_HOST 
      MYSQL_PASSWORD: *MYSQL_PASSWORD
      MYSQL_DATABASE: *MYSQL_DATABASE
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    depends_on: 
      - percona 
    
  percona:
    environment:
      MYSQL_USER: *MYSQL_USER
      MYSQL_HOST: *MYSQL_HOST 
      MYSQL_PASSWORD: *MYSQL_PASSWORD
      MYSQL_DATABASE: *MYSQL_DATABASE
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    image: percona:5.7
    ports: 
      - "3306:3306"
